export const NEW_MEDIA_REQUEST = 'NEW_MEDIA_REQUEST';
export const NEW_MEDIA_SUCCESS = 'NEW_MEDIA_SUCCESS';
export const NEW_MEDIA_RESET = 'NEW_MEDIA_RESET';
export const NEW_MEDIA_FAIL = 'NEW_MEDIA_FAIL';

export const ALL_MEDIA_REQUEST = 'ALL_MEDIA_REQUEST';
export const ALL_MEDIA_SUCCESS = 'ALL_MEDIA_SUCCESS';
export const ALL_MEDIA_FAIL = 'ALL_MEDIA_FAIL';

export const MEDIA_DETAILS_REQUEST = 'MEDIA_DETAILS_REQUEST';
export const MEDIA_DETAILS_SUCCESS = 'MEDIA_DETAILS_SUCCESS';
export const MEDIA_DETAILS_FAIL = 'MEDIA_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';